name: " 🏗 Lint & Build"

on: 
  workflow_call:

jobs:
  node-build:
    runs-on: ubuntu-latest
    steps:
        - name: "☁️ checkout repository"
          uses: actions/checkout@v3

          - name: "🔧 setup node"  
            uses: actions/setup-node@v2
            with:
              node-version: '16'
              cache: 'npm'

          - name: "🔧 install yarn@latest"
            run: npm install -g  yarn@latest

          - name: "📦 install dependencies"
            run: npm install
            with:
              cache: 'dependencies'
              working-directory: Frontend

          – run: npm run lint
          – run: npm run build

      
