version: "3"

# docker-compose.ci.yml extends from base, not worrying about
# networks as only for integration testing via github actions

services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
      deploy:
        x-aws-autoscaling: 
          cpu: 75
        resources:
          limits:
            cpus: '1.0'
            memory: 2048M
    ports:
      - "3000:80"
      
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4096M
    ports:
      - "3002:80"
  
