version: "3"

# docker-compose.yml extends from base which sets the base images
# setting up the network separation between front and back ends

services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    depends_on:
      - api
    ports:
      - "3000:80"
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - front
      - back
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3002:80"
    networks:
      - back

networks:
  front:
    name: front
  back:
    name: back

